
from pydantic import Field, validator
from typing import List, Optional, Union, Literal
from sdks.novavision.src.base.model import Package, Image, Inputs, Configs, Outputs, Response, Request, Output, Input, Config, Detection, ROI, KeyPoints


class Detection(Detection):
    """
    Extends the base Detection to ensure we accept the keyPoints
    generated by the YOLO Segmentation model.
    """
    keyPoints: Optional[List[KeyPoints]] = None
    # We also accept 'angle' if OBB mode was used, though unlikely for segmentation
    angle: Optional[float] = None

class InputDetections(Input):
    name: Literal["inputDetections"] = "inputDetections"
    value: Union[List[Detection], List[ROI]]
    type: str = "list"

    class Config:
        title = "Detections/ROI"

class InputImage(Input):
    name: Literal["inputImage"] = "inputImage"
    value: Union[List[Image], Image]
    type: str = "object"

    @validator("type", pre=True, always=True)
    def set_type_based_on_value(cls, value, values):
        value = values.get('value')
        if isinstance(value, Image):
            return "object"
        elif isinstance(value, list):
            return "list"

    class Config:
        title = "Image"

class OutputDetections(Output):
    name: Literal["outputDetections"] = "outputDetections"
    value: Union[List[Detection], List[ROI]]
    type: str = "list"

    class Config:
        title = "Detections"



class BoundingRectangleInputs(Inputs):
    inputImage: InputImage
    inputDetections: InputDetections

    class Config:
        title = "Bounding Rectangle Inputs"


class BoundingRectangleOutputs(Outputs):
    outputDetections: OutputDetections

    class Config:
        title = "Bounding Rectangle Outputs"

class BoundingRectangleRequest(Request):
    inputs: Union[BoundingRectangleInputs]
    configs: Configs

    class Config:
        json_schema_extra = {
            "target": "configs"
        }

class BoundingRectangleResponse(Response):
    outputs: BoundingRectangleOutputs

    class Config:
        title = "Bounding Rectangle Response"

class BoundingRectangleExecutor(Config):
    name: Literal["BoundingRectangle"] = "BoundingRectangle"
    value: Union[BoundingRectangleRequest, BoundingRectangleResponse]
    type: Literal["object"] = "object"
    field: Literal["option"] = "option"

    class Config:
        title = "Bounding Rectangle Executor"
        json_schema_extra = {
            "target": {
                "value": 0
            }
        }

class ConfigExecutor(Config):
    name: Literal["ConfigExecutor"] = "ConfigExecutor"
    value: Union[BoundingRectangleExecutor]
    type: Literal["executor"] = "executor"
    field: Literal["dependentDropdownlist"] = "dependentDropdownlist"
    restart: Literal[True] = True

    class Config:
        title = "Task"
        json_schema_extra = {
            "target": "value"
        }

class PackageConfigs(Configs):
    executor: ConfigExecutor

    class Config:
        title = "Package Configurations"

class PackageModel(Package):
    configs: PackageConfigs
    type: Literal["component"] = "component"
    name: Literal["BoundingRectangle"] = "BoundingRectangle"

    class Config:
        title = "Package Model"